# Generated by Django 3.2.8 on 2021-10-11 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=250)),
                ('news_content', models.TextField(blank=True)),
                ('news_create', models.DateField(auto_now_add=True)),
                ('news_update', models.DateField(auto_now=True)),
                ('news_image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categories')),
            ],
        ),
    ]
